- hosts: localhost
  become: yes
  
  tasks:
    - name: make instance 1
      ec2: image= ami-33db9803
           instance_type= t2.micro
           aws_access_key= Secret
           aws_secret_key= Secret_key
           keypair= aws_ansible
           instance_tags='{ "Name":"Provisioning" , "Group":"launch-wizard-1" }'
           region= us-west-2
           group= launch-wizard-1
           wait=true
      register: ec2_info

    - debug: var=ec2_info
    - debug: var=item
      with_items: ec2_info.instance_ids

    - add_host: hostname={{ item.public_ip }} groupname=ec2host1
      with_items: ec2_info.instances

    - name: wait for instances to listen on port:22
      wait_for:
        state=started
        host={{ item.public_ip }}
        port=22
      with_items: ec2_info.instances

- hosts: ec2host1
  gather_facts: True
  become: yes
  
  tasks:
- name: install package for maven
  apt: name="{{item}}" state=present
  with_items:
   - maven
   - git
   - default-jdk

- name: clone boxfuse from git
  git:
    repo: 'https://github.com/boxfuse/boxfuse-sample-java-war-hello.git'
    dest: /home/boxfuse
    clone: yes

- name: run mvn package
  shell: mvn package
  args:
    chdir: /home/boxfuse

- name: fetch .war files
  fetch:
    src: /home/boxfuse/target/hello-1.0.war
    dest: /

  tasks:
    - name: make instance 2
      ec2: image= ami-33db9807
           instance_type= t2.micro
           aws_access_key= Secret
           aws_secret_key= Secret_key
           keypair= aws_ansible
           instance_tags='{ "Name":"Tomcat" , "Group":"launch-wizard-2" }'
           region= us-west-2
           group= launch-wizard-2
           wait= true
           
      register: ec2_info

    - debug: var=ec2_info
    - debug: var=item
      with_items: ec2_info.instance_ids

    - add_host: hostname={{ item.public_ip }} groupname=ec2host2
      with_items: ec2_info.instances

    - name: wait for instances to listen on port:22
      wait_for:
        state=started
        host={{ item.public_ip }}
        port=22
      with_items: ec2_info.instances

- hosts: ec2host2
  gather_facts: True
  become: yes
  
- name: install tomcat9
  apt:
    name: tomcat9
    state: present

- name: copy .war files
  copy:
    src: /158.160.30.66/home/boxfuse/target/hello-1.0.war
    dest: /var/lib/tomcat9/webapps

    
     
